package com.greedmitya.albcalculator.assets
val ingredientNameMap = mapOf(
    "T2_AGARIC" to "Arcane Agaric",
    "T1_ALCHEMY_EXTRACT_LEVEL1" to "Basic Arcane Extract",
    "BEAR_ICE_CREAM" to "Bear Ice Cream",
    "BLAZING_BONES" to "Blazing Bones",
    "BRIGHTLEAF_COMFREY" to "Brightleaf Comfrey",
    "BURNING_EMBER" to "Burning Ember",
    "CHOPPED_FISH" to "Chopped Fish",
    "COMMON_ARCANE_EXTRACT" to "Common Arcane Extract",
    "CORN_HOOCH" to "Corn Hooch",
    "COWS_BUTTER" to "Cow's Butter",
    "CRUSHED_ARCTIC" to "Crushed Arctic",
    "CRUSHED_ROCKROOT" to "Crushed Rockroot",
    "CRUSHED_SUNFLARE" to "Crushed Sunflare",
    "CURSED_JAWBONE" to "Cursed Jawbone",
    "DEMONIC_SHARD" to "Demonic Shard",
    "DRAGON_TEETH" to "Dragon Teeth",
    "ELDERFLOWER_SYRUP" to "Elderflower Syrup",
    "ELVISH_NECTAR" to "Elvish Nectar",
    "ENCHANTED_MANDRAKE_ROOT" to "Enchanted Mandrake Root",
    "EXCELLENT_RUNESTONE_TOOTH" to "Excellent Runestone Tooth",
    "EXCEPTIONAL_RUNESTONE_TOOTH" to "Exceptional Runestone Tooth",
    "EXPLOSIVE_MUSHROOM" to "Explosive Mushroom",
    "EYE_OF_GIANT" to "Eye of Giant",
    "FERMENTED_SPIRIT" to "Fermented Spirit",
    "FIERY_BERRIES" to "Fiery Berries",
    "FINE_SYLVIAN_ROOT" to "Fine Sylvian Root",
    "FROST_FLOWERS" to "Frost Flowers",
    "GLOWING_MOSS" to "Glowing Moss",
    "GOATS_MILK" to "Goat's Milk",
    "GOBLIN_NOSE_RING" to "Goblin Nose Ring",
    "GOBLIN_TEETH" to "Goblin Teeth",
    "GREAT_ARCANE_EXTRACT" to "Great Arcane Extract",
    "GREMLIN_TOOTH" to "Gremlin Tooth",
    "GRIFFIN_TALON" to "Griffin Talon",
    "HOLY_ORCHID" to "Holy Orchid",
    "LARGE_ARCANE_EXTRACT" to "Large Arcane Extract",
    "MOUNTAIN_BLOOD" to "Mountain Blood",
    "RARE_ARCANE_EXTRACT" to "Rare Arcane Extract",
    "RUGGED_WEREWOLF_FANGS" to "Rugged Werewolf Fangs",
    "SILVERWEED_ROOT" to "Silverweed Root",
    "SLIPPERY_EEL" to "Slippery Eel",
    "UNICORN_HAIR" to "Unicorn Hair"
)
