package com.greedmitya.albcalculator.model
/*
T2_POTION_HEAL, T2_POTION_HEAL@1, T2_POTION_HEAL@2, T2_POTION_HEAL@3,
T4_POTION_HEAL, T4_POTION_HEAL@1, T4_POTION_HEAL@2, T4_POTION_HEAL@3,
T6_POTION_HEAL, T6_POTION_HEAL@1, T6_POTION_HEAL@2, T6_POTION_HEAL@3,

T2_POTION_ENERGY, T2_POTION_ENERGY@1, T2_POTION_ENERGY@2, T2_POTION_ENERGY@3,
T4_POTION_ENERGY, T4_POTION_ENERGY@1, T4_POTION_ENERGY@2, T4_POTION_ENERGY@3,
T6_POTION_ENERGY, T6_POTION_ENERGY@1, T6_POTION_ENERGY@2, T6_POTION_ENERGY@3,

T3_POTION_REVIVE, T3_POTION_REVIVE@1, T3_POTION_REVIVE@2, T3_POTION_REVIVE@3,
T5_POTION_REVIVE, T5_POTION_REVIVE@1, T5_POTION_REVIVE@2, T5_POTION_REVIVE@3,
T7_POTION_REVIVE, T7_POTION_REVIVE@1, T7_POTION_REVIVE@2, T7_POTION_REVIVE@3,

T3_POTION_STONESKIN, T3_POTION_STONESKIN@1, T3_POTION_STONESKIN@2, T3_POTION_STONESKIN@3,
T5_POTION_STONESKIN, T5_POTION_STONESKIN@1, T5_POTION_STONESKIN@2, T5_POTION_STONESKIN@3,
T7_POTION_STONESKIN, T7_POTION_STONESKIN@1, T7_POTION_STONESKIN@2, T7_POTION_STONESKIN@3,

T3_POTION_SLOWFIELD, T3_POTION_SLOWFIELD@1, T3_POTION_SLOWFIELD@2, T3_POTION_SLOWFIELD@3,
T5_POTION_SLOWFIELD, T5_POTION_SLOWFIELD@1, T5_POTION_SLOWFIELD@2, T5_POTION_SLOWFIELD@3,
T7_POTION_SLOWFIELD, T7_POTION_SLOWFIELD@1, T7_POTION_SLOWFIELD@2, T7_POTION_SLOWFIELD@3,

T4_POTION_COOLDOWN, T4_POTION_COOLDOWN@1, T4_POTION_COOLDOWN@2, T4_POTION_COOLDOWN@3,
T6_POTION_COOLDOWN, T6_POTION_COOLDOWN@1, T6_POTION_COOLDOWN@2, T6_POTION_COOLDOWN@3,
T8_POTION_COOLDOWN, T8_POTION_COOLDOWN@1, T8_POTION_COOLDOWN@2, T8_POTION_COOLDOWN@3,

T4_POTION_BERSERK, T4_POTION_BERSERK@1, T4_POTION_BERSERK@2, T4_POTION_BERSERK@3,
T6_POTION_BERSERK, T6_POTION_BERSERK@1, T6_POTION_BERSERK@2, T6_POTION_BERSERK@3,
T8_POTION_BERSERK, T8_POTION_BERSERK@1, T8_POTION_BERSERK@2, T8_POTION_BERSERK@3,

T4_POTION_LAVA, T4_POTION_LAVA@1, T4_POTION_LAVA@2, T4_POTION_LAVA@3,
T6_POTION_LAVA, T6_POTION_LAVA@1, T6_POTION_LAVA@2, T6_POTION_LAVA@3,
T8_POTION_LAVA, T8_POTION_LAVA@1, T8_POTION_LAVA@2, T8_POTION_LAVA@3,

T4_POTION_GATHER, T4_POTION_GATHER@1, T4_POTION_GATHER@2, T4_POTION_GATHER@3,
T6_POTION_GATHER, T6_POTION_GATHER@1, T6_POTION_GATHER@2, T6_POTION_GATHER@3,
T8_POTION_GATHER, T8_POTION_GATHER@1, T8_POTION_GATHER@2, T8_POTION_GATHER@3,

T4_POTION_TORNADO, T4_POTION_TORNADO@1, T4_POTION_TORNADO@2, T4_POTION_TORNADO@3,
T6_POTION_TORNADO, T6_POTION_TORNADO@1, T6_POTION_TORNADO@2, T6_POTION_TORNADO@3,
T8_POTION_TORNADO, T8_POTION_TORNADO@1, T8_POTION_TORNADO@2, T8_POTION_TORNADO@3,

T3_POTION_MOB_RESET, T3_POTION_MOB_RESET@1, T3_POTION_MOB_RESET@2, T3_POTION_MOB_RESET@3,
T5_POTION_MOB_RESET, T5_POTION_MOB_RESET@1, T5_POTION_MOB_RESET@2, T5_POTION_MOB_RESET@3,
T7_POTION_MOB_RESET, T7_POTION_MOB_RESET@1, T7_POTION_MOB_RESET@2, T7_POTION_MOB_RESET@3,

T3_POTION_CLEANSE2, T3_POTION_CLEANSE2@1, T3_POTION_CLEANSE2@2, T3_POTION_CLEANSE2@3,
T5_POTION_CLEANSE2, T5_POTION_CLEANSE2@1, T5_POTION_CLEANSE2@2, T5_POTION_CLEANSE2@3,
T7_POTION_CLEANSE2, T7_POTION_CLEANSE2@1, T7_POTION_CLEANSE2@2, T7_POTION_CLEANSE2@3,

T3_POTION_ACID, T3_POTION_ACID@1, T3_POTION_ACID@2, T3_POTION_ACID@3,
T5_POTION_ACID, T5_POTION_ACID@1, T5_POTION_ACID@2, T5_POTION_ACID@3,
T7_POTION_ACID, T7_POTION_ACID@1, T7_POTION_ACID@2, T7_POTION_ACID@3,

T8_POTION_CLEANSE, T8_POTION_CLEANSE@1, T8_POTION_CLEANSE@2, T8_POTION_CLEANSE@3


 */